services:
  goalapi.api-client:
    class: GoalAPI\SDKBundle\GoalAPISDK\APIClient\Guzzle\Client
    arguments: ['%goalapi.base_url%', '%goalapi.apikey%']

  goalapi.performer.get_subscription:
    class: GoalAPI\SDKBundle\GoalAPISDK\CallPerformers\GetSubscription
    public: false

  goalapi.performer.get_tournaments:
    class: GoalAPI\SDKBundle\GoalAPISDK\CallPerformers\GetTournaments
    public: false

  goalapi.performer.get_tournament:
    class: GoalAPI\SDKBundle\GoalAPISDK\CallPerformers\GetTournament
    public: false

  goalapi.performer.get_seasons:
    class: GoalAPI\SDKBundle\GoalAPISDK\CallPerformers\GetSeasons
    public: false

  goalapi.performer.get_season:
    class: GoalAPI\SDKBundle\GoalAPISDK\CallPerformers\GetSeason
    public: false

  goalapi.performer.get_stages:
    class: GoalAPI\SDKBundle\GoalAPISDK\CallPerformers\GetStages
    public: false

  goalapi.performer.get_stage:
    class: GoalAPI\SDKBundle\GoalAPISDK\CallPerformers\GetStage
    public: false

  goalapi.performer.get_standings:
    class: GoalAPI\SDKBundle\GoalAPISDK\CallPerformers\GetStandings
    public: false

  goalapi.performer.get_squads:
    class: GoalAPI\SDKBundle\GoalAPISDK\CallPerformers\GetSquads
    public: false

  goalapi.performer.get_squad:
    class: GoalAPI\SDKBundle\GoalAPISDK\CallPerformers\GetSquad
    public: false

  goalapi.performer.get_matches:
    class: GoalAPI\SDKBundle\GoalAPISDK\CallPerformers\GetMatches
    public: false

  goalapi.performer.get_match:
    class: GoalAPI\SDKBundle\GoalAPISDK\CallPerformers\GetMatch
    public: false

  goalapi.denormalizer.subscription:
    class: GoalAPI\SDKBundle\GoalAPISDK\Serializer\Normalizer\SubscriptionDenormalizer
    public: false

  goalapi.denormalizer.tournament:
    class: GoalAPI\SDKBundle\GoalAPISDK\Serializer\Normalizer\TournamentDenormalizer
    public: false

  goalapi.denormalizer.season:
    class: GoalAPI\SDKBundle\GoalAPISDK\Serializer\Normalizer\SeasonDenormalizer
    public: false

  goalapi.denormalizer.stage:
    class: GoalAPI\SDKBundle\GoalAPISDK\Serializer\Normalizer\StageDenormalizer
    public: false

  goalapi.denormalizer.standings:
    class: GoalAPI\SDKBundle\GoalAPISDK\Serializer\Normalizer\StandingsTableDenormalizer
    public: false

  goalapi.denormalizer.team:
    class: GoalAPI\SDKBundle\GoalAPISDK\Serializer\Normalizer\TeamDenormalizer
    public: false

  goalapi.denormalizer.squad:
    class: GoalAPI\SDKBundle\GoalAPISDK\Serializer\Normalizer\SquadDenormalizer
    public: false

  goalapi.denormalizer.match:
    class: GoalAPI\SDKBundle\GoalAPISDK\Serializer\Normalizer\MatchDenormalizer
    public: false

  goalapi.denormalizer.player_in_squad:
    class: GoalAPI\SDKBundle\GoalAPISDK\Serializer\Normalizer\PlayerInSquadDenormalizer
    public: false

  goalapi.denormalizer.player:
    class: GoalAPI\SDKBundle\GoalAPISDK\Serializer\Normalizer\PlayerDenormalizer
    public: false

  goalapi.denormalizer.territory:
    class: GoalAPI\SDKBundle\GoalAPISDK\Serializer\Normalizer\TerritoryDenormalizer
    public: false

  goalapi.denormalizer.array:
    class: GoalAPI\SDKBundle\Serializer\Denormalizer\ArrayDenormalizer
    public: false

  goalapi.serializer.encoder.impl.json.encode:
    public: false
    class: 'Symfony\Component\Serializer\Encoder\JsonEncode'
    arguments:
      0: 480

  goalapi.serializer.encoder.impl.json.decode:
    public: false
    class: 'Symfony\Component\Serializer\Encoder\JsonDecode'
    arguments:
      0: false

  goalapi.serializer.encoder.json:
    public: false
    class: 'Symfony\Component\Serializer\Encoder\JsonEncoder'
    arguments:
      0: '@goalapi.serializer.encoder.impl.json.encode'
      1: '@goalapi.serializer.encoder.impl.json.decode'

  goalapi.serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      0:
        - '@goalapi.denormalizer.array'
        - '@goalapi.denormalizer.subscription'
        - '@goalapi.denormalizer.tournament'
        - '@goalapi.denormalizer.season'
        - '@goalapi.denormalizer.stage'
        - '@goalapi.denormalizer.match'
        - '@goalapi.denormalizer.standings'
        - '@goalapi.denormalizer.team'
        - '@goalapi.denormalizer.squad'
        - '@goalapi.denormalizer.player_in_squad'
        - '@goalapi.denormalizer.player'
        - '@goalapi.denormalizer.territory'
      1:
        - '@goalapi.serializer.encoder.json'
    public: false

  goalapi.sdk:
    class: GoalAPI\SDKBundle\GoalAPISDK
    calls:
     - [setApiClient, ['@goalapi.api-client']]
     - [setSerializer, ['@goalapi.serializer']]
     - [addCallPerformer, ['getSubscription', '@goalapi.performer.get_subscription']]
     - [addCallPerformer, ['getTournaments', '@goalapi.performer.get_tournaments']]
     - [addCallPerformer, ['getTournament', '@goalapi.performer.get_tournament']]
     - [addCallPerformer, ['getSeasons', '@goalapi.performer.get_seasons']]
     - [addCallPerformer, ['getSeason', '@goalapi.performer.get_season']]
     - [addCallPerformer, ['getStages', '@goalapi.performer.get_stages']]
     - [addCallPerformer, ['getStage', '@goalapi.performer.get_stage']]
     - [addCallPerformer, ['getStandings', '@goalapi.performer.get_standings']]
     - [addCallPerformer, ['getSquads', '@goalapi.performer.get_squads']]
     - [addCallPerformer, ['getSquad', '@goalapi.performer.get_squad']]
     - [addCallPerformer, ['getMatches', '@goalapi.performer.get_matches']]
     - [addCallPerformer, ['getMatch', '@goalapi.performer.get_match']]
